### ISSUE TITLE
Impossible to setup supervisor

### ISSUE THREAD

**Issue by sycured** [software-to-hardware/erpnext-vat-mtd#5]
Hello,
I'm following your doc about CentOS 8 and when I do `bench setup supervisor`, I obtain:
```
WARN: superuser privileges required for this command
```
SELinux is in targeted mode during this setup
Regards

**Comment by Paul-STHL** [comment]
Interestingly, when I tried it today I didn't get such an error.

Superuser privileges are required to restart the _supervisord_ daemon but it doesn't matter in this case because we reboot at the end of the guide.
