### ISSUE TITLE
Using sudo to install frappe-bench

### ISSUE THREAD

**Issue by ryuliantoro** [software-to-hardware/erpnext-vat-mtd#6]
Hi,

Following your guide (a clear and concise guide by the way) one can successfully create frappe-bench for development. 
But not when proceeding to setting up production (as mentioned [in other issue here](https://github.com/software-to-hardware/erpnext-vat-mtd/issues/5#issue-659912821)).

There is a note from [Trent's blog](https://murgatroyd.za.net/?p=832) on installing on Debian that the `pip3 install --user frappe-bench` MUST be done with sudo. But doing so will make the subsequent bench command not found (as mentioned in this discuss [topic](https://discuss.erpnext.com/t/setup-production-problem-superuser-privileges-required/53708/13))

What is your suggestion?
Thanks.

**Comment by Paul-STHL** [comment]
"_pip3 install --user frappe-bench MUST be done with sudo._" I suspect that will result in frappe-bench only accessible to the root user. I'll run through the guide just now to check for any inconsistencies.
